---
version: "2.0"

endpoints: 
  nodeendpoint123:
    kind: ip

services:
  node:
    image: quay.io/vpavlin0/wakash:9437f9a
    expose:
      - port: 60000
        as: 60000
        proto: tcp
        to:
          - global: true
            ip: nodeendpoint123

      - port: 8003
        as: 8003
        proto: tcp
        to:
          - global: true
            ip: nodeendpoint123

      - port: 9005
        proto: udp
        to:
          - global: true
            ip: nodeendpoint123

      - port: 8000
        as: 8000
        proto: tcp
        to:
          - global: true
            ip: nodeendpoint123

      - port: 80
        as: 80
        to:
          - global: true
            ip: nodeendpoint123
    params:
      storage:
        certs:
          mount: /etc/letsencrypt
    env:
      - DOMAIN=
      - NODEKEY=
      - IP_ADDR=
    args:
      - --relay=true
      - --filter=true
      - --lightpush=true
      - --pubsub-topic=/waku/2/default-waku/proto
      - --pubsub-topic=/waku/2/dev-waku/proto
      - --keep-alive=true
      - --peer-exchange=true
      - --max-connections=300
      - --dns-discovery=true
      - --dns-discovery-url=enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im
      - --discv5-discovery=true
      - --discv5-udp-port=9005
      - --discv5-enr-auto-update=True
      - --log-level=DEBUG
      - --metrics-server=True
      - --metrics-server-port=8003
      - --metrics-server-address=0.0.0.0
      - --store=true
      - --store-message-retention-policy=time:2592000

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: certs
            size: 5Gi
            attributes:
              persistent: true
              class: beta3


  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        node: 
          denom: uakt
          amount: 100000

deployment:
  node:
    westcoast:
      profile: node
      count: 1

